### ISSUE TITLE
Cityflow installation failed 

### ISSUE THREAD

**Issue by IAFutur** [cityflow-project/CityFlow#117]
Hi all ! 

I've been trying to install cityflow for a while and I am still stuck with it ... Here is what I've done: install anaconda, create an env with `python=3.6 and tensorflow=2.1`. Then I installed `cmake` with the following [link](https://anaconda.org/anaconda/cmake) and `gym` with this [one link](https://anaconda.org/conda-forge/gym). I am on windows 10 premium. But after using git to clone the repo, when I use `pip install .` in my new env I receive the following error. I would really appreciate if you could help with this ! Thanks in advance 😉

```
(tf_cpu) C:\Users\VArri\CityFlow>pip install .
Processing c:\users\varri\cityflow
Building wheels for collected packages: CityFlow
  Building wheel for CityFlow (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\VArri\anaconda3\envs\tf_cpu\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\VArri\\AppData\\Local\\Temp\\pip-req-build-2bldtl4i\\setup.py'"'"'; __file__='"'"'C:\\Users\\VArri\\AppData\\Local\\Temp\\pip-req-build-2bldtl4i\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\VArri\AppData\Local\Temp\pip-wheel-dz3so72o'
       cwd: C:\Users\VArri\AppData\Local\Temp\pip-req-build-2bldtl4i\
  Complete output (51 lines):
  running bdist_wheel
  running build
  running build_ext
  -- Building for: NMake Makefiles
  CMake Error at CMakeLists.txt:2 (project):
    Generator

      NMake Makefiles

    does not support platform specification, but platform

      x64

    was specified.


  CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
  CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
  -- Configuring incomplete, errors occurred!
  See also "C:/Users/VArri/AppData/Local/Temp/pip-req-build-2bldtl4i/build/temp.win-amd64-3.6/Release/CMakeFiles/CMakeOutput.log".
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\VArri\AppData\Local\Temp\pip-req-build-2bldtl4i\setup.py", line 69, in <module>
      zip_safe=False
    File "C:\Users\VArri\anaconda3\envs\tf_cpu\lib\site-packages\setuptools\__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "C:\Users\VArri\anaconda3\envs\tf_cpu\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "C:\Users\VArri\anaconda3\envs\tf_cpu\lib\distutils\dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "C:\Users\VArri\anaconda3\envs\tf_cpu\lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "C:\Users\VArri\anaconda3\envs\tf_cpu\lib\site-packages\wheel\bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "C:\Users\VArri\anaconda3\envs\tf_cpu\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Users\VArri\anaconda3\envs\tf_cpu\lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "C:\Users\VArri\anaconda3\envs\tf_cpu\lib\distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "C:\Users\VArri\anaconda3\envs\tf_cpu\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Users\VArri\anaconda3\envs\tf_cpu\lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "C:\Users\VArri\AppData\Local\Temp\pip-req-build-2bldtl4i\setup.py", line 32, in run
      self.build_extension(ext)
    File "C:\Users\VArri\AppData\Local\Temp\pip-req-build-2bldtl4i\setup.py", line 56, in build_extension
      subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
    File "C:\Users\VArri\anaconda3\envs\tf_cpu\lib\subprocess.py", line 311, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['cmake', 'C:\\Users\\VArri\\AppData\\Local\\Temp\\pip-req-build-2bldtl4i', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\Users\\VArri\\AppData\\Local\\Temp\\pip-req-build-2bldtl4i\\build\\lib.win-amd64-3.6', '-DPYTHON_EXECUTABLE=C:\\Users\\VArri\\anaconda3\\envs\\tf_cpu\\python.exe', '-DVERSION="0.1"', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\\Users\\VArri\\AppData\\Local\\Temp\\pip-req-build-2bldtl4i\\build\\lib.win-amd64-3.6', '-A', 'x64']' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for CityFlow
  Running setup.py clean for CityFlow
Failed to build CityFlow
Installing collected packages: CityFlow
    Running setup.py install for CityFlow ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\VArri\anaconda3\envs\tf_cpu\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\VArri\\AppData\\Local\\Temp\\pip-req-build-2bldtl4i\\setup.py'"'"'; __file__='"'"'C:\\Users\\VArri\\AppData\\Local\\Temp\\pip-req-build-2bldtl4i\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\VArri\AppData\Local\Temp\pip-record-8uut22ag\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\VArri\anaconda3\envs\tf_cpu\Include\CityFlow'
         cwd: C:\Users\VArri\AppData\Local\Temp\pip-req-build-2bldtl4i\
    Complete output (53 lines):
    running install
    running build
    running build_ext
    -- Building for: NMake Makefiles
    CMake Error at CMakeLists.txt:2 (project):
      Generator

        NMake Makefiles

      does not support platform specification, but platform

        x64

      was specified.


    CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
    CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
    -- Configuring incomplete, errors occurred!
    See also "C:/Users/VArri/AppData/Local/Temp/pip-req-build-2bldtl4i/build/temp.win-amd64-3.6/Release/CMakeFiles/CMakeOutput.log".
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\VArri\AppData\Local\Temp\pip-req-build-2bldtl4i\setup.py", line 69, in <module>
        zip_safe=False
      File "C:\Users\VArri\anaconda3\envs\tf_cpu\lib\site-packages\setuptools\__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "C:\Users\VArri\anaconda3\envs\tf_cpu\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\Users\VArri\anaconda3\envs\tf_cpu\lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "C:\Users\VArri\anaconda3\envs\tf_cpu\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Users\VArri\anaconda3\envs\tf_cpu\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "C:\Users\VArri\anaconda3\envs\tf_cpu\lib\distutils\command\install.py", line 545, in run
        self.run_command('build')
      File "C:\Users\VArri\anaconda3\envs\tf_cpu\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Users\VArri\anaconda3\envs\tf_cpu\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Users\VArri\anaconda3\envs\tf_cpu\lib\distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "C:\Users\VArri\anaconda3\envs\tf_cpu\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Users\VArri\anaconda3\envs\tf_cpu\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Users\VArri\AppData\Local\Temp\pip-req-build-2bldtl4i\setup.py", line 32, in run
        self.build_extension(ext)
      File "C:\Users\VArri\AppData\Local\Temp\pip-req-build-2bldtl4i\setup.py", line 56, in build_extension
        subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
      File "C:\Users\VArri\anaconda3\envs\tf_cpu\lib\subprocess.py", line 311, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', 'C:\\Users\\VArri\\AppData\\Local\\Temp\\pip-req-build-2bldtl4i', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\Users\\VArri\\AppData\\Local\\Temp\\pip-req-build-2bldtl4i\\build\\lib.win-amd64-3.6', '-DPYTHON_EXECUTABLE=C:\\Users\\VArri\\anaconda3\\envs\\tf_cpu\\python.exe', '-DVERSION="0.1"', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\\Users\\VArri\\AppData\\Local\\Temp\\pip-req-build-2bldtl4i\\build\\lib.win-amd64-3.6', '-A', 'x64']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\VArri\anaconda3\envs\tf_cpu\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\VArri\\AppData\\Local\\Temp\\pip-req-build-2bldtl4i\\setup.py'"'"'; __file__='"'"'C:\\Users\\VArri\\AppData\\Local\\Temp\\pip-req-build-2bldtl4i\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\VArri\AppData\Local\Temp\pip-record-8uut22ag\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\VArri\anaconda3\envs\tf_cpu\Include\CityFlow' Check the logs for full command output.
```

**Comment by only-changer** [comment]
For Windows users, it is recommended to run CityFlow under Windows Subsystem for Linux (WSL) or use docker.

**Comment by Freedomisgood** [comment]
I wonder if cityflow supports cp3.8.10 on ubuntu20.04 in the wsl2? I failed.


```bash
      [ 84%] Built target cityflow_lib
      Scanning dependencies of target cityflow
      [ 92%] Building CXX object CMakeFiles/cityflow.dir/src/cityflow.cpp.o
      In file included from /home/zjumrli/downloads/CityFlow/extern/pybind11/include/pybind11/pytypes.h:12,
                       from /home/zjumrli/downloads/CityFlow/extern/pybind11/include/pybind11/cast.h:13,
                       from /home/zjumrli/downloads/CityFlow/extern/pybind11/include/pybind11/attr.h:13,
                       from /home/zjumrli/downloads/CityFlow/extern/pybind11/include/pybind11/pybind11.h:49,
                       from /home/zjumrli/downloads/CityFlow/src/cityflow.cpp:4:
      /home/zjumrli/downloads/CityFlow/extern/pybind11/include/pybind11/detail/common.h:112:10: fatal error: Python.h: No such file or directory
        112 | #include <Python.h>
            |          ^~~~~~~~~~
      compilation terminated.
      make[3]: *** [CMakeFiles/cityflow.dir/build.make:63: CMakeFiles/cityflow.dir/src/cityflow.cpp.o] Error 1
      make[2]: *** [CMakeFiles/Makefile2:117: CMakeFiles/cityflow.dir/all] Error 2
      make[1]: *** [CMakeFiles/Makefile2:124: CMakeFiles/cityflow.dir/rule] Error 2
      make: *** [Makefile:118: cityflow] Error 2
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/zjumrli/downloads/CityFlow/setup.py", line 60, in <module>
          setup(
        File "/home/zjumrli/.local/share/virtualenvs/zjumrli-3ZSlgD17/lib/python3.8/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
        File "/home/zjumrli/.local/share/virtualenvs/zjumrli-3ZSlgD17/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/home/zjumrli/.local/share/virtualenvs/zjumrli-3ZSlgD17/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/home/zjumrli/.local/share/virtualenvs/zjumrli-3ZSlgD17/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/home/zjumrli/.local/share/virtualenvs/zjumrli-3ZSlgD17/lib/python3.8/site-packages/setuptools/dist.py", line 963, in run_command
          super().run_command(command)
        File "/home/zjumrli/.local/share/virtualenvs/zjumrli-3ZSlgD17/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/zjumrli/.local/share/virtualenvs/zjumrli-3ZSlgD17/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 368, in run
          self.run_command("build")
        File "/home/zjumrli/.local/share/virtualenvs/zjumrli-3ZSlgD17/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/zjumrli/.local/share/virtualenvs/zjumrli-3ZSlgD17/lib/python3.8/site-packages/setuptools/dist.py", line 963, in run_command
          super().run_command(command)
        File "/home/zjumrli/.local/share/virtualenvs/zjumrli-3ZSlgD17/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/zjumrli/.local/share/virtualenvs/zjumrli-3ZSlgD17/lib/python3.8/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/home/zjumrli/.local/share/virtualenvs/zjumrli-3ZSlgD17/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/zjumrli/.local/share/virtualenvs/zjumrli-3ZSlgD17/lib/python3.8/site-packages/setuptools/dist.py", line 963, in run_command
          super().run_command(command)
        File "/home/zjumrli/.local/share/virtualenvs/zjumrli-3ZSlgD17/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/zjumrli/downloads/CityFlow/setup.py", line 32, in run
          self.build_extension(ext)
        File "/home/zjumrli/downloads/CityFlow/setup.py", line 57, in build_extension
          subprocess.check_call(['cmake', '--build', '.', '--target', 'cityflow'] + build_args, cwd=self.build_temp)
        File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'cityflow', '--config', 'Release', '--', '-j2']' returned non-zero exit status 2.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for CityFlow
  Running setup.py clean for CityFlow
Failed to build CityFlow
```
