### ISSUE TITLE
urllib.error.URLError: <urlopen error unknown url type: e>

### ISSUE THREAD

**Issue by AnniRen** [cityflow-project/CityFlow#118]
Could you please tell me how to solve this problem?

D:\Anaconda3\python.exe E:/CityFlow-master/CityFlow-master/tools/converter/converter.py
Converting sumo net file atlanta_sumo.net.xml
Traceback (most recent call last):
  File "E:/CityFlow-master/CityFlow-master/tools/converter/converter.py", line 536, in <module>
    main(args)
  File "E:/CityFlow-master/CityFlow-master/tools/converter/converter.py", line 501, in main
    net = sumolib.net.readNet(os.path.join(os.getcwd(),args.sumonet), withPrograms=True)
  File "F:\SUMO\tools\sumolib\net\__init__.py", line 691, in readNet
    parse(filename, netreader)
  File "D:\Anaconda3\lib\xml\sax\__init__.py", line 33, in parse
    parser.parse(source)
  File "D:\Anaconda3\lib\xml\sax\expatreader.py", line 105, in parse
    source = saxutils.prepare_input_source(source)
  File "D:\Anaconda3\lib\xml\sax\saxutils.py", line 364, in prepare_input_source
    f = urllib.request.urlopen(source.getSystemId())
  File "D:\Anaconda3\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "D:\Anaconda3\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "D:\Anaconda3\lib\urllib\request.py", line 548, in _open
    'unknown_open', req)
  File "D:\Anaconda3\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "D:\Anaconda3\lib\urllib\request.py", line 1389, in unknown_open
    raise URLError('unknown url type: %s' % type)
urllib.error.URLError: <urlopen error unknown url type: e>

Process finished with exit code 1

**Comment by only-changer** [comment]
For Windows users, it is recommended to run CityFlow under Windows Subsystem for Linux (WSL) or use docker.
