### ISSUE TITLE
can't generate m_n  grid roads when m>n, while using generator tools 

### ISSUE THREAD

**Issue by LiangZhang1996** [cityflow-project/CityFlow#119]
When the row of the roadnet larger than the columns, get the error like the following:
``` python
python generate_grid_scenario.py 2 1 
```
```python
Traceback (most recent call last):
  File "generate_grid_scenario.py", line 103, in <module>
    json.dump(gridToRoadnet(**grid), open(os.path.join(args.dir, args.roadnetFile), "w"), indent=2)
  File "/Users/zhangliang/Desktop/CityFlow/tools/generator/generate_json_from_grid.py", line 212, in gridToRoadnet
    x[i][j] = x[i][j - 1] + rowDistances[i - 1]
IndexError: list index out of range
```

**Comment by LiangZhang1996** [comment]
This problem has been fiexd, just add one judgement.
I changed the code at line 209 of `generate_json_from_grid.py`
The changed code as follows:
```python
    if rowNumber<=columnNumber:
        for i in range(rowNumber):
            for j in range(columnNumber):
                if j > 0:
                    x[i][j] = x[i][j - 1] + rowDistances[i - 1]
                    y[i][j] = y[i][j - 1]
                elif i > 0:
                    x[i][j] = x[i - 1][j]
                    y[i][j] = y[i - 1][j] + columnDistances[j - 1]
                else:
                    x[i][j] = -outRowDistance
                    y[i][j] = -outColumnDistance
    elif rowNumber>columnNumber:
        for j in range(columnNumber):
            for i in range(rowNumber):
                if i > 0:
                    x[i][j] = x[i - 1][j]
                    y[i][j] = y[i - 1][j] + columnDistances[j - 1]

                elif j > 0:
                    x[i][j] = x[i][j - 1] + rowDistances[i - 1]
                    y[i][j] = y[i][j - 1]
                else:
                    x[i][j] = -outRowDistance
                    y[i][j] = -outColumnDistance
```
The origin code as follows:
```python
for i in range(rowNumber):
        for j in range(columnNumber):
            if j > 0:
                x[i][j] = x[i][j - 1] + rowDistances[i - 1]
                y[i][j] = y[i][j - 1]
            elif i > 0:
                x[i][j] = x[i - 1][j]
                y[i][j] = y[i - 1][j] + columnDistances[j - 1]
            else:
                x[i][j] = -outRowDistance
                y[i][j] = -outColumnDistance
```

The author is recommended to  fix this problem.
