### ISSUE TITLE
Cityflow Installationn

### ISSUE THREAD

**Issue by mandharepa** [cityflow-project/CityFlow#137]
Hello all,
I am trying to install cityflow on Oracle Virtual box but getting the following error on windows 10...

$ sudo pip install .
Processing /media/sf_PhD_data/execution/colight-master/CityFlow
Building wheels for collected packages: CityFlow
  Building wheel for CityFlow (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-graxh3bh/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-graxh3bh/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-k710sfqb
       cwd: /tmp/pip-req-build-graxh3bh/
  Complete output (35 lines):
  running bdist_wheel
  running build
  running build_ext
  CMake Error: The current CMakeCache.txt directory /tmp/pip-req-build-graxh3bh/CMakeCache.txt is different than the directory /media/sf_PhD_data/execution/colight-master/CityFlow where CMakeCache.txt was created. This may result in binaries being created in the wrong place. If you are not sure, reedit the CMakeCache.txt
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-req-build-graxh3bh/setup.py", line 60, in <module>
      setup(
    File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 144, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/lib/python3/dist-packages/wheel/bdist_wheel.py", line 223, in run
      self.run_command('build')
    File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/lib/python3.8/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-req-build-graxh3bh/setup.py", line 32, in run
      self.build_extension(ext)
    File "/tmp/pip-req-build-graxh3bh/setup.py", line 56, in build_extension
      subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
    File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['cmake', '/tmp/pip-req-build-graxh3bh', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/tmp/pip-req-build-graxh3bh/build/lib.linux-x86_64-3.8', '-DPYTHON_EXECUTABLE=/usr/bin/python3', '-DVERSION="0.1"', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for CityFlow
  Running setup.py clean for CityFlow
Failed to build CityFlow
Installing collected packages: CityFlow
    Running setup.py install for CityFlow ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-graxh3bh/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-graxh3bh/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-oi9cw0zl/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.8/CityFlow
         cwd: /tmp/pip-req-build-graxh3bh/
    Complete output (37 lines):
    running install
    running build
    running build_ext
    CMake Error: The current CMakeCache.txt directory /tmp/pip-req-build-graxh3bh/CMakeCache.txt is different than the directory /media/sf_PhD_data/execution/colight-master/CityFlow where CMakeCache.txt was created. This may result in binaries being created in the wrong place. If you are not sure, reedit the CMakeCache.txt
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-graxh3bh/setup.py", line 60, in <module>
        setup(
      File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 144, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.8/distutils/command/install.py", line 589, in run
        self.run_command('build')
      File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.8/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/pip-req-build-graxh3bh/setup.py", line 32, in run
        self.build_extension(ext)
      File "/tmp/pip-req-build-graxh3bh/setup.py", line 56, in build_extension
        subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
      File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', '/tmp/pip-req-build-graxh3bh', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/tmp/pip-req-build-graxh3bh/build/lib.linux-x86_64-3.8', '-DPYTHON_EXECUTABLE=/usr/bin/python3', '-DVERSION="0.1"', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-graxh3bh/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-graxh3bh/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-oi9cw0zl/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.8/CityFlow Check the logs for full command output.

how to resolve it?
thanks in advanced.... :)

**Comment by Sheagu** [comment]
I'm stuck with a similar issue. Have you fix it?

**Comment by zhc134** [comment]
Did you run `pip install .` at CityFlow root directory?

**Comment by Sirius-1110** [comment]
How to install cityflow into a specified virtual enviorment? Is `pip install .` available?
