### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by ThisIsIsaac** [cityflow-project/CityFlow#14]
**OS:** CentOS7
**Python:** 3.6.8
**Cmake:** 3.13.5

**executed command:** `sudo ~/.virtualenvs/cityflow/bin/pip3 install .`

```
    ERROR: Command errored out with exit status 1:
     command: /home/isaac/.virtualenvs/cityflow/bin/python3.6 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-2g19e6tp/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-2g19e6tp/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-z0iogwys/install-record.txt --single-version-externally-managed --compile --install-headers /home/isaac/.virtualenvs/cityflow/include/site/python3.6/CityFlow
         cwd: /tmp/pip-req-build-2g19e6tp/
    Complete output (117 lines):
    running install
    running build
    running build_ext
    -- The C compiler identification is GNU 4.8.5
    -- The CXX compiler identification is GNU 4.8.5
    -- Check for working C compiler: /bin/cc
    -- Check for working C compiler: /bin/cc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Check for working CXX compiler: /bin/c++
    -- Check for working CXX compiler: /bin/c++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- Found Submodule: extern/pybind11/CMakeLists.txt
    -- Found Submodule: extern/rapidjson/include
    -- Found PythonInterp: /home/isaac/.virtualenvs/cityflow/bin/python3.6 (found version "3.6.8")
    -- Found PythonLibs: python3.6m
    -- pybind11 v2.3.dev0
    -- Looking for pthread.h
    -- Looking for pthread.h - found
    -- Looking for pthread_create
    -- Looking for pthread_create - not found
    -- Looking for pthread_create in pthreads
    -- Looking for pthread_create in pthreads - not found
    -- Looking for pthread_create in pthread
    -- Looking for pthread_create in pthread - found
    -- Found Threads: TRUE
    -- Boost version: 1.53.0
    -- Found the following Boost libraries:
    --   thread
    --   chrono
    --   system
    --   date_time
    --   atomic
    -- Boost version: 1.53.0
    -- Found the following Boost libraries:
    --   program_options
    -- Performing Test HAS_FLTO
    -- Performing Test HAS_FLTO - Success
    -- LTO enabled
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /tmp/pip-req-build-2g19e6tp/build/temp.linux-x86_64-3.6
    Scanning dependencies of target cityflow_lib
    [  7%] Building CXX object src/CMakeFiles/cityflow_lib.dir/engine/engine.cpp.o
    [ 14%] Building CXX object src/CMakeFiles/cityflow_lib.dir/utility/utility.cpp.o
    In file included from /tmp/pip-req-build-2g19e6tp/src/utility/utility.cpp:1:0:
    /tmp/pip-req-build-2g19e6tp/src/utility/utility.h:84:54: error: expected class-name before ‘{’ token
         class JsonFormatError: public std::runtime_error {
                                                          ^
    /tmp/pip-req-build-2g19e6tp/src/utility/utility.h: In constructor ‘CityFlow::JsonFormatError::JsonFormatError(const string&)’:
    /tmp/pip-req-build-2g19e6tp/src/utility/utility.h:86:79: error: expected class-name before ‘(’ token
             explicit JsonFormatError(const std::string &info) : std::runtime_error(info){}
                                                                                   ^
    /tmp/pip-req-build-2g19e6tp/src/utility/utility.h:86:79: error: expected ‘{’ before ‘(’ token
    gmake[2]: *** [src/CMakeFiles/cityflow_lib.dir/utility/utility.cpp.o] Error 1
    gmake[2]: *** Waiting for unfinished jobs....
    In file included from /tmp/pip-req-build-2g19e6tp/src/vehicle/vehicle.h:4:0,
                     from /tmp/pip-req-build-2g19e6tp/src/flow/flow.h:4,
                     from /tmp/pip-req-build-2g19e6tp/src/engine/engine.h:4,
                     from /tmp/pip-req-build-2g19e6tp/src/engine/engine.cpp:1:
    /tmp/pip-req-build-2g19e6tp/src/utility/utility.h:84:54: error: expected class-name before ‘{’ token
         class JsonFormatError: public std::runtime_error {
                                                          ^
    /tmp/pip-req-build-2g19e6tp/src/utility/utility.h: In constructor ‘CityFlow::JsonFormatError::JsonFormatError(const string&)’:
    /tmp/pip-req-build-2g19e6tp/src/utility/utility.h:86:79: error: expected class-name before ‘(’ token
             explicit JsonFormatError(const std::string &info) : std::runtime_error(info){}
                                                                                   ^
    /tmp/pip-req-build-2g19e6tp/src/utility/utility.h:86:79: error: expected ‘{’ before ‘(’ token
    /tmp/pip-req-build-2g19e6tp/src/engine/engine.cpp: In member function ‘bool CityFlow::Engine::loadConfig(const string&)’:
    /tmp/pip-req-build-2g19e6tp/src/engine/engine.cpp:81:28: error: ‘const class CityFlow::JsonFormatError’ has no member named ‘what’
                 std::cerr << e.what() << std::endl;
                                ^
    /tmp/pip-req-build-2g19e6tp/src/engine/engine.cpp: In member function ‘bool CityFlow::Engine::loadFlow(const string&)’:
    /tmp/pip-req-build-2g19e6tp/src/engine/engine.cpp:149:28: error: ‘const class CityFlow::JsonFormatError’ has no member named ‘what’
                 std::cerr << e.what() << std::endl;
                                ^
    gmake[2]: *** [src/CMakeFiles/cityflow_lib.dir/engine/engine.cpp.o] Error 1
    gmake[1]: *** [src/CMakeFiles/cityflow_lib.dir/all] Error 2
    gmake: *** [all] Error 2
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-2g19e6tp/setup.py", line 68, in <module>
        zip_safe=False
      File "/home/isaac/.virtualenvs/cityflow/lib/python3.6/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib64/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib64/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/isaac/.virtualenvs/cityflow/lib/python3.6/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib64/python3.6/distutils/command/install.py", line 556, in run
        self.run_command('build')
      File "/usr/lib64/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib64/python3.6/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/lib64/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-req-build-2g19e6tp/setup.py", line 32, in run
        self.build_extension(ext)
      File "/tmp/pip-req-build-2g19e6tp/setup.py", line 57, in build_extension
        subprocess.check_call(['cmake', '--build', '.'] + build_args, cwd=self.build_temp)
      File "/usr/lib64/python3.6/subprocess.py", line 311, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j2']' returned non-zero exit status 2.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/isaac/.virtualenvs/cityflow/bin/python3.6 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-2g19e6tp/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-2g19e6tp/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-z0iogwys/install-record.txt --single-version-externally-managed --compile --install-headers /home/isaac/.virtualenvs/cityflow/include/site/python3.6/CityFlow Check the logs for full command output.
```

**Comment by zhc134** [comment]
Thanks Isaac! We forgot to include <stdexcept>, which is not a problem in GNU 5.4.0. We've added <stdexcept> for older GNU.

**Comment by zhc134** [comment]
Thanks Isaac! We forgot to include `<stdexcept>`, which is not a problem in our compiler GNU 5.4.0. We've added `<stdexcept>` for older GNU.
