### ISSUE TITLE
 ”pip install .“引起的错误

### ISSUE THREAD

**Issue by 1dSHallRed** [cityflow-project/CityFlow#153]
运行pip install .出现下来错误，救救孩子吧
(cityflow) root@514d12b46104:/opt/cityFlow# pip install .
mProcessing /opt/cityFlow
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: CityFlow
  Building wheel for CityFlow (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /root/anaconda3/envs/cityflow/bin/python3.6 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/opt/cityFlow/setup.py'"'"'; __file__='"'"'/opt/cityFlow/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-5of9mg6u
       cwd: /opt/cityFlow/
  Complete output (42 lines):
  running bdist_wheel
  running build
  running build_ext
  CMake Error at CMakeLists.txt:51 (message):
    The submodule extern/pybind11/CMakeLists.txt was not downloaded!
    GIT_SUBMODULE was turned off or failed.  Please update submodules and try
    again.

  -- Configuring incomplete, errors occurred!
  See also "/opt/cityFlow/build/temp.linux-x86_64-3.6/CMakeFiles/CMakeOutput.log".
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/opt/cityFlow/setup.py", line 69, in <module>
      zip_safe=False
    File "/root/anaconda3/envs/cityflow/lib/python3.6/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/root/anaconda3/envs/cityflow/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/root/anaconda3/envs/cityflow/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/root/anaconda3/envs/cityflow/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/root/anaconda3/envs/cityflow/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "/root/anaconda3/envs/cityflow/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/root/anaconda3/envs/cityflow/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/root/anaconda3/envs/cityflow/lib/python3.6/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/root/anaconda3/envs/cityflow/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/root/anaconda3/envs/cityflow/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/opt/cityFlow/setup.py", line 32, in run
      self.build_extension(ext)
    File "/opt/cityFlow/setup.py", line 56, in build_extension
      subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
    File "/root/anaconda3/envs/cityflow/lib/python3.6/subprocess.py", line 291, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['cmake', '/opt/cityFlow', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/opt/cityFlow/build/lib.linux-x86_64-3.6', '-DPYTHON_EXECUTABLE=/root/anaconda3/envs/cityflow/bin/python3.6', '-DVERSION="0.1"', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for CityFlow
  Running setup.py clean for CityFlow
Failed to build CityFlow
Installing collected packages: CityFlow
    Running setup.py install for CityFlow ... error
    ERROR: Command errored out with exit status 1:
     command: /root/anaconda3/envs/cityflow/bin/python3.6 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/opt/cityFlow/setup.py'"'"'; __file__='"'"'/opt/cityFlow/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-9wtte_61/install-record.txt --single-version-externally-managed --compile --install-headers /root/anaconda3/envs/cityflow/include/python3.6m/CityFlow
         cwd: /opt/cityFlow/
    Complete output (58 lines):
    running install
    running build
    running build_ext
    -- The C compiler identification is GNU 7.5.0
    -- The CXX compiler identification is GNU 7.5.0
    -- Check for working C compiler: /usr/bin/cc
    -- Check for working C compiler: /usr/bin/cc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Check for working CXX compiler: /usr/bin/c++
    -- Check for working CXX compiler: /usr/bin/c++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    CMake Error at CMakeLists.txt:51 (message):
      The submodule extern/pybind11/CMakeLists.txt was not downloaded!
      GIT_SUBMODULE was turned off or failed.  Please update submodules and try
      again.

    -- Configuring incomplete, errors occurred!
    See also "/opt/cityFlow/build/temp.linux-x86_64-3.6/CMakeFiles/CMakeOutput.log".
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/opt/cityFlow/setup.py", line 69, in <module>
        zip_safe=False
      File "/root/anaconda3/envs/cityflow/lib/python3.6/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/root/anaconda3/envs/cityflow/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/root/anaconda3/envs/cityflow/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/root/anaconda3/envs/cityflow/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/root/anaconda3/envs/cityflow/lib/python3.6/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/root/anaconda3/envs/cityflow/lib/python3.6/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/root/anaconda3/envs/cityflow/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/root/anaconda3/envs/cityflow/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/root/anaconda3/envs/cityflow/lib/python3.6/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/root/anaconda3/envs/cityflow/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/root/anaconda3/envs/cityflow/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/opt/cityFlow/setup.py", line 32, in run
        self.build_extension(ext)
      File "/opt/cityFlow/setup.py", line 56, in build_extension
        subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
      File "/root/anaconda3/envs/cityflow/lib/python3.6/subprocess.py", line 291, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', '/opt/cityFlow', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/opt/cityFlow/build/lib.linux-x86_64-3.6', '-DPYTHON_EXECUTABLE=/root/anaconda3/envs/cityflow/bin/python3.6', '-DVERSION="0.1"', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /root/anaconda3/envs/cityflow/bin/python3.6 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/opt/cityFlow/setup.py'"'"'; __file__='"'"'/opt/cityFlow/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-9wtte_61/install-record.txt --single-version-externally-managed --compile --install-headers /root/anaconda3/envs/cityflow/include/python3.6m/CityFlow Check the logs for full command output.

**Comment by zhc134** [comment]
CityFlow relies on two external submodules [pybind11] and [rapidjson], please check if you have [git] installed. If [git] is properly installed, try running `git submodule update --init` manually then run `pip install .`
