### ISSUE TITLE
`Converter.py` error

### ISSUE THREAD

**Issue by ThisIsIsaac** [cityflow-project/CityFlow#16]
**python version: ** 3.6.8

**command:** `python converter.py --sumonet /home/isaac/rainbow_dqn_traffic_signal_control/sumo_config/tlcs.net.xml --cityflownet /home/isaac/rainbow_dqn_traffic_signal_control/sumo_config/tlcs.json`

**output message:**
```
/usr/share/sumo/tools
Converting sumo net file /home/isaac/rainbow_dqn_traffic_signal_control/sumo_config/tlcs.net.xml
Start processing 1 traffic lights
TL
Traceback (most recent call last):
  File "converter.py", line 535, in <module>
    main(args)
  File "converter.py", line 514, in main
    final_intersections = get_final_intersections(net,tls_dict,edge_dict)
  File "converter.py", line 450, in get_final_intersections
    intersection = node_to_intersection(node,tls_dict,edge_dict)
  File "converter.py", line 399, in node_to_intersection
    for phase,duration in tls_dict[nodeid]._programs['0']._phases:
TypeError: 'Phase' object is not iterable
```

**Input file:** 
[tlcs.net.xml.zip](https://github.com/cityflow-project/CityFlow/files/3500222/tlcs.net.xml.zip)

**Comment by zhc134** [comment]
@only-changer @Chacha-Chen can you look into what is happening?

**Comment by only-changer** [comment]
I have tried your sumonet on WSL(py3.6.8) and MACOS(py3.7.4), but I didn't see the bug.
My suggestions are:
1. check your environment varible SUMO_HOME;
2. reinstall sumotool (pip install https://akreidieh.s3.amazonaws.com/sumo/flow-0.2.0/sumotools-0.1.0-py3-none-any.whl), see more at https://github.com/flow-project/flow/issues/102
If you still see the bug, please tell us.

**Comment by Hzfengsy** [comment]
@ThisIsIsaac Is the problem solved? If so, please close this issue. Thank you!
