### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by ThisIsIsaac** [cityflow-project/CityFlow#17]
**OS:** CentOS7
**Python:** 3.6.8
**Cmake:** 3.13.5
**executed command:** `sudo ~/.virtualenvs/cityflow/bin/pip3 install .`
**`gcc` & `g++`:** 4.8.5

**Error message:**
```
Installing collected packages: CityFlow
  Running setup.py install for CityFlow ... error
    ERROR: Command errored out with exit status 1:
     command: /home/isaac/.virtualenvs/cityflow/bin/python3.6 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-b1n7sori/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-b1n7sori/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-3d_a1qba/install-record.txt --single-version-externally-managed --compile --install-headers /home/isaac/.virtualenvs/cityflow/include/site/python3.6/CityFlow
         cwd: /tmp/pip-req-build-b1n7sori/
    Complete output (111 lines):
    running install
    running build
    running build_ext
    -- The C compiler identification is GNU 4.8.5
    -- The CXX compiler identification is GNU 4.8.5
    -- Check for working C compiler: /bin/cc
    -- Check for working C compiler: /bin/cc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Check for working CXX compiler: /bin/c++
    -- Check for working CXX compiler: /bin/c++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- Found Submodule: extern/pybind11/CMakeLists.txt
    -- Found Submodule: extern/rapidjson/include
    -- Found PythonInterp: /home/isaac/.virtualenvs/cityflow/bin/python3.6 (found version "3.6.8")
    -- Found PythonLibs: python3.6m
    -- pybind11 v2.3.dev0
    -- Looking for pthread.h
    -- Looking for pthread.h - found
    -- Looking for pthread_create
    -- Looking for pthread_create - not found
    -- Looking for pthread_create in pthreads
    -- Looking for pthread_create in pthreads - not found
    -- Looking for pthread_create in pthread
    -- Looking for pthread_create in pthread - found
    -- Found Threads: TRUE
    -- Boost version: 1.53.0
    -- Found the following Boost libraries:
    --   thread
    --   chrono
    --   system
    --   date_time
    --   atomic
    -- Boost version: 1.53.0
    -- Found the following Boost libraries:
    --   program_options
    -- Performing Test HAS_FLTO
    -- Performing Test HAS_FLTO - Success
    -- LTO enabled
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /tmp/pip-req-build-b1n7sori/build/temp.linux-x86_64-3.6
    Scanning dependencies of target cityflow_lib
    [  7%] Building CXX object src/CMakeFiles/cityflow_lib.dir/utility/utility.cpp.o
    [ 14%] Building CXX object src/CMakeFiles/cityflow_lib.dir/engine/engine.cpp.o
    [ 21%] Building CXX object src/CMakeFiles/cityflow_lib.dir/flow/flow.cpp.o
    [ 28%] Building CXX object src/CMakeFiles/cityflow_lib.dir/flow/route.cpp.o
    [ 35%] Building CXX object src/CMakeFiles/cityflow_lib.dir/roadnet/roadnet.cpp.o
    [ 42%] Building CXX object src/CMakeFiles/cityflow_lib.dir/roadnet/trafficlight.cpp.o
    [ 50%] Building CXX object src/CMakeFiles/cityflow_lib.dir/vehicle/router.cpp.o
    [ 57%] Building CXX object src/CMakeFiles/cityflow_lib.dir/vehicle/vehicle.cpp.o
    [ 64%] Building CXX object src/CMakeFiles/cityflow_lib.dir/vehicle/lanechange.cpp.o
    [ 71%] Linking CXX static library libcityflow_lib.a
    [ 71%] Built target cityflow_lib
    Scanning dependencies of target cityflow_test
    Scanning dependencies of target cityflow
    [ 78%] Building CXX object CMakeFiles/cityflow_test.dir/src/test.cpp.o
    [ 85%] Building CXX object CMakeFiles/cityflow.dir/src/simulator.cpp.o
    In file included from /tmp/pip-req-build-b1n7sori/extern/pybind11/include/pybind11/pytypes.h:12:0,
                     from /tmp/pip-req-build-b1n7sori/extern/pybind11/include/pybind11/cast.h:13,
                     from /tmp/pip-req-build-b1n7sori/extern/pybind11/include/pybind11/attr.h:13,
                     from /tmp/pip-req-build-b1n7sori/extern/pybind11/include/pybind11/pybind11.h:44,
                     from /tmp/pip-req-build-b1n7sori/src/simulator.cpp:3:
    /tmp/pip-req-build-b1n7sori/extern/pybind11/include/pybind11/detail/common.h:112:20: fatal error: Python.h: No such file or directory
     #include <Python.h>
                        ^
    compilation terminated.
    gmake[2]: *** [CMakeFiles/cityflow.dir/src/simulator.cpp.o] Error 1
    gmake[1]: *** [CMakeFiles/cityflow.dir/all] Error 2
    gmake[1]: *** Waiting for unfinished jobs....
    [ 92%] Linking CXX executable cityflow_test
    [ 92%] Built target cityflow_test
    gmake: *** [all] Error 2
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-b1n7sori/setup.py", line 68, in <module>
        zip_safe=False
      File "/home/isaac/.virtualenvs/cityflow/lib/python3.6/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib64/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib64/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/isaac/.virtualenvs/cityflow/lib/python3.6/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib64/python3.6/distutils/command/install.py", line 556, in run
        self.run_command('build')
      File "/usr/lib64/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib64/python3.6/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/lib64/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-req-build-b1n7sori/setup.py", line 32, in run
        self.build_extension(ext)
      File "/tmp/pip-req-build-b1n7sori/setup.py", line 57, in build_extension
        subprocess.check_call(['cmake', '--build', '.'] + build_args, cwd=self.build_temp)
      File "/usr/lib64/python3.6/subprocess.py", line 311, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j2']' returned non-zero exit status 2.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/isaac/.virtualenvs/cityflow/bin/python3.6 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-b1n7sori/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-b1n7sori/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-3d_a1qba/install-record.txt --single-version-externally-managed --compile --install-headers /home/isaac/.virtualenvs/cityflow/include/site/python3.6/CityFlow Check the logs for full command output.
```

**Comment by soodoshll** [comment]
We haven't tested on Centos yet. I guess installing python-devel might help.

**Comment by ThisIsIsaac** [comment]
I have installed python-devel 3.6 (via `yum install rh-python36-python-devel`) but I get the same error. 

I have checked that `Python.h` file is located here: `/opt/rh/rh-python36/root/usr/include/python3.6m/Python.h` but the error says:

```
    [ 85%] Building CXX object CMakeFiles/cityflow.dir/src/simulator.cpp.o
    In file included from /tmp/pip-req-build-cxfhg6ue/extern/pybind11/include/pybind11/pytypes.h:12:0,
                     from /tmp/pip-req-build-cxfhg6ue/extern/pybind11/include/pybind11/cast.h:13,
                     from /tmp/pip-req-build-cxfhg6ue/extern/pybind11/include/pybind11/attr.h:13,
                     from /tmp/pip-req-build-cxfhg6ue/extern/pybind11/include/pybind11/pybind11.h:44,
                     from /tmp/pip-req-build-cxfhg6ue/src/simulator.cpp:3:
    /tmp/pip-req-build-cxfhg6ue/extern/pybind11/include/pybind11/detail/common.h:112:20: fatal error: Python.h: No such file or directory
     #include <Python.h>
                        ^
    compilation terminated.
```

Do I have to manually include path to my `Python.h`?

**Comment by ThisIsIsaac** [comment]
## Problem

Installing python-devel 3.6 (via yum install rh-python36-python-devel) does not add path to `Python.h` to `INCLUDE_DIRECTORY`, resulting to the above error.

## Solution

Added 
```
include_directories(/opt/rh/rh-python36/root/usr/include/python3.6m)
```

To `CMakeLists.txt`
